### ISSUE TITLE
Integrate old duplicate finder code

### ISSUE THREAD

**Issue by dmgciubotaru** [imirica/DuplicateFinder#4]
Integrate the old duplicate finder code into the new GUI app.
Add a status bar to indicate the current status of the program (ready, scanning )
Display the list of files as text

**Comment by imirica** [comment]
"Display the list of files as text" - Should I save the paths of the files in a .txt and then save the .txt file in a default location?

**Comment by dmgciubotaru** [comment]
> "Display the list of files as text" - Should I save the paths of the files in a .txt and then save the .txt file in a default location?

Not really, you can use a text box and display the names of the files. This will be enough for now, we'll build in top of it later

**Comment by imirica** [comment]
ok
